"""add mattin_id to incidents

Revision ID: cf0927083f5f
Revises: 0f32352911c0
Create Date: 2026-01-08 16:08:56.615467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0927083f5f'
down_revision: Union[str, Sequence[str], None] = '0f32352911c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('mattin_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'mattin_id')
    # ### end Alembic commands ###
